# Generated by Django 3.2 on 2021-07-31 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enroll.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=1000000)),
                ('message_date', models.CharField(default=0, max_length=1000)),
                ('user', models.CharField(max_length=1000000)),
                ('belongs_to_room', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('user_inv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Room_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='seen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_ka_name', models.CharField(max_length=10000)),
                ('special_id', models.CharField(max_length=10000)),
                ('roomnm', models.CharField(default=0, max_length=10000)),
                ('time_of_reject', models.CharField(default=0, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Selectoptions',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('city_name', models.CharField(max_length=70)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('unique_key', models.CharField(default=0, max_length=100, validators=[enroll.models.Selectoptions.validate_ukey])),
                ('incr', models.CharField(default=1, max_length=1)),
                ('date_time', models.CharField(default=1, max_length=30)),
                ('combKey', models.CharField(default=1, max_length=5)),
                ('time_check', models.CharField(default=1, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user_involved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ka_name', models.CharField(max_length=1000)),
                ('user_ka_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='waiting_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_room', models.CharField(max_length=1000)),
                ('users_message', models.CharField(max_length=1000)),
                ('users_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Grp_admin',
            fields=[
                ('related_room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='enroll.room')),
                ('G_a', models.CharField(max_length=1000)),
                ('preference', models.CharField(max_length=10)),
                ('he_is_adm_of', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='weather_ackno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(default=1, max_length=10000)),
                ('time_of_message', models.CharField(default=0, max_length=1000)),
                ('messages_alert', models.CharField(default=0, max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_items', models.TextField()),
                ('schedule_date', models.DateField(validators=[enroll.models.Scheduled.validate_date])),
                ('schedule_time', models.TimeField(validators=[enroll.models.Scheduled.validate_time])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='expired_scheduledList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_items', models.TextField()),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
