# Generated by Django 3.2 on 2021-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin_Unpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_id', models.IntegerField()),
                ('pin_ka_id', models.IntegerField()),
                ('pin_permission', models.CharField(max_length=20)),
            ],
        ),
    ]
