# Generated by Django 3.2 on 2021-07-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_pin_unpin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin_unpin',
            name='pin_ka_id',
            field=models.CharField(max_length=1000),
        ),
    ]
